import Navbar from "../../components/navbar"
import Footer from "../../components/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
 return (
   <>
   <Navbar/>
    <div>
     
     {children}

    </div>
   <Footer/>
   
   </>

  )
}
